version: 2
updates:
  - package-ecosystem: npm
    directory: ./backend/
    schedule:
      interval: weekly
    groups:
      backend:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: ./frontend/
    schedule:
      interval: weekly
    groups:
      mobile:
        patterns:
          - "*"
    ignore:
      - dependency-name: "tailwindcss"
        versions: ["*"]
      
