openapi: 3.1.0

info:
  title: Dearly API
  summary: Dearly makes connecting with loved ones easy.
  description: |
    Dearly is a private family-sharing app that bridges generational gaps and makes staying connected easier and more meaningful. The platform allows families to share photos, voice memos, and other media in a secure, invite-only space. With two thoughtfully designed modes, Dearly caters to every generation: a streamlined, user-friendly interface for those less familiar with technology and a dynamic, feature-rich experience for younger users.
  version: 1.0.0

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
    ValidationError:
      type: object
      required:
        - message
        - errors
      properties:
        message:
          type: string
        errors:
          type: array
          items:
            type: object
            required:
              - path
              - message
            properties:
              path:
                type: string
              message:
                type: string
    User:
      type: object
      properties:
        name:
          type: string
          description: Display name of the user.
        username:
          type: string
          description: The username of the user.
        id:
          type: string
          format: uuid
          example: 5e91507e-5630-4efd-9fd4-799178870b10
          description: A unique identifier for the user.
        mode:
          type: string
          enum: ["BASIC", "ADVANCED", null]
          description: The mode for the user (e.g., "BASIC" or "ADVANCED"). Default to "BASIC" if no mode is provided.
        profilePhoto:
          type: string
          nullable: true
          description: A URL to the user's profile photo.
        notificationsEnabled:
          type: boolean
          description: True when user enables notification.
      required:
        - name
        - username
        - mode

paths:
  /healthcheck:
    get:
      tags:
        - Healthcheck
      summary: Healthcheck endpoint
      description: Pings the server to check the health of the current server
      responses:
        "200":
          description: Success!
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    enum:
                      - OK

  /api/v1/users:
    post:
      tags:
        - User Endpoints
      summary: Creates a user
      description: Creates a user from the specified body (with ID being the decoded ID from JWT).
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
                  description: Display name of the user.
                username:
                  type: string
                  minLength: 1
                  description: The username of the user.
                mode:
                  type: string
                  enum: ["BASIC", "ADVANCED", null]
                  description: The mode for the user (e.g., "BASIC" or "ADVANCED").
                profilePhoto:
                  type: string
                  nullable: true
                  description: A URL to the user's profile photo.
              required:
                - name
                - username
              additionalProperties: true
      responses:
        201:
          description: Successfully created a User
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: Malformed request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Error"
                  - $ref: "#/components/schemas/ValidationError"
        401:
          description: Unauthorized due to invalid JWT
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        409:
          description: Same JWT creates multiple users or username already exists
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/v1/users/{id}:
    get:
      tags:
        - User Endpoints
      summary: Gets a user
      description: Gets the user by their UUID.
      parameters:
        - name: id
          in: path
          description: ID of the user to get
          required: true
          schema:
            type: string
            format: uuid
            example: 5e91507e-5630-4efd-9fd4-799178870b10
      responses:
        200:
          description: Successfully retrieved a User
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: Malformed request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Error"
                  - $ref: "#/components/schemas/ValidationError"
        401:
          description: Unauthorized due to invalid JWT
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/v1/users/me:
    put:
      tags:
        - User Endpoints
      summary: Updates a user
      description: Updates the user profile for the currently authenticated user (identified by the decoded ID from JWT).
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
                  description: Display name of the user.
                username:
                  type: string
                  minLength: 1
                  description: The username of the user.
                mode:
                  type: string
                  enum: ["BASIC", "ADVANCED", null]
                  description: The mode for the user (e.g., "BASIC" or "ADVANCED").
                profilePhoto:
                  type: string
                  nullable: true
                  description: A URL to the user's profile photo.
                notificationsEnabled:
                  type: boolean
                  description: True when user wants to receive notifications.
              additionalProperties: true
      responses:
        200:
          description: Successfully updated the user profile
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          description: Malformed request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Error"
                  - $ref: "#/components/schemas/ValidationError"
        401:
          description: Unauthorized due to invalid JWT
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      tags:
        - User Endpoints
      summary: Deletes a user
      description: Deletes the user account for the currently authenticated user (identified by the decoded ID from JWT).
      security:
        - BearerAuth: []
      responses:
        200:
          description: Successfully delete user
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Successfully delete user"
        400:
          description: Malformed request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Error"
                  - $ref: "#/components/schemas/ValidationError"
        401:
          description: Unauthorized due to invalid JWT
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/v1/users/devices:
    post:
      tags:
        - User Endpoints
      summary: Register user's device token
      description: Registers an Expo Device Token for the currently authenticated user to receive notifications.
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                expoToken:
                  type: string
                  description: The Expo Device Token of the user.
              required:
                - expoToken
      responses:
        200:
          description: Successfully registered the device token
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                description: Array of user's device tokens
        400:
          description: Malformed request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Error"
                  - $ref: "#/components/schemas/ValidationError"
        401:
          description: Unauthorized due to invalid JWT
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        404:
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      tags:
        - User Endpoints
      summary: Remove user's device token
      description: Removes a registered Expo Device Token for the currently authenticated user to not receive notifications.
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                expoToken:
                  type: string
                  description: The Expo Device Token of the user.
              required:
                - expoToken
      responses:
        200:
          description: Successfully removed the device token
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                description: Array of user's remaining device tokens
        400:
          description: Malformed request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Error"
                  - $ref: "#/components/schemas/ValidationError"
        401:
          description: Unauthorized due to invalid JWT
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
