version: "3"

tasks:
  frontend:install:
    desc: "Install frontend dependencies"
    cmds:
      - cd frontend && bun install

  backend:install:
    desc: "Install backend dependencies"
    cmds:
      - cd backend && bun install

  frontend:lint:
    desc: "Lint frontend"
    cmds:
      - cd frontend && bun lint:fix

  backend:lint:
    desc: "Lint backend"
    cmds:
      - cd backend && bun lint:fix

  frontend:dev:
    desc: "Run frontend development server with backend development server"
    cmds:
      - cd frontend && bun run dev

  frontend:prod:
    desc: "Run frontend development server with backend deployed server"
    cmds:
      - cd frontend && bun run prod

  backend:dev:
    desc: "Run backend development server with Docker database"
    cmds:
      - cd backend && bun run dev

  backend:prod:
    desc: "Run backend production server with production database"
    cmds:
      - cd backend && bun start

  db:up:
    desc: "Start local database in Docker"
    cmds:
      - cd backend && bun run db:up

  db:down:
    desc: "Stop local database in Docker"
    cmds:
      - cd backend && bun run db:down

  db:generate:
    desc: "Generate SQL for database schema"
    cmds:
      - cd backend && bun generate

  db:migrate:
    desc: "Apply database migrations"
    cmds:
      - cd backend && bun migrate

  db:studio:
    desc: "Run local Drizzle studio"
    cmds:
      - cd backend && bun db:studio

  db:generate:migrate:
    desc: "Apply SQL generation and migration"
    deps: [db:generate, db:migrate]

  format:
    desc: "Format frontend and backend code"
    cmds:
      - cd backend && bun format
      - cd frontend && bun format

  install:
    desc: "Install frontend and backend dependencies"
    deps: [frontend:install, backend:install]

  test:
    desc: "Run tests in backend, if run with -- <test_file_path> you can run a single test file or you can specifiy which file to merge"
    cmds:
      - cd backend && source scripts/test.sh {{.CLI_ARGS}}

  generate:
    desc: "Generate Schema from OpenAPI Specification"
    cmds:
      - cd backend && bun run gen

  clean:
    desc: "Clean up temporary files"
    cmds:
      - rm -rf node_modules bun.lockb package-lock.json
      - cd backend && rm -rf node_modules bun.lockb package-lock.json gen
      - cd frontend && rm -rf node_modules bun.lockb package-lock.json .expo gen
