import { Context } from "hono";
import { Status } from "../../constants/http";
import { handleAppError } from "../../utilities/errors/app-error";
import { parseUUID } from "../../utilities/api/uuid";
import { InvitationService } from "./service";
import { CreateInviteResponse, VerifyTokenResponse } from "../../types/api/routes/invite";

/**
 * Interface that defines the operations available for handling group invitations in the application.
 * It includes methods for creating an invitation token for a group and verifying an invitation token to join a group.
 */
export interface InvitationController {
  /**
   * Creates an invitation token for a group, allowing a user to invite others to join the group.
   * The token is generated by the system and is valid for a set period, usually 7 days.
   *
   * @param ctx - The context of the HTTP request, containing information such as the group ID and the current user.
   * @returns A promise that resolves to a JSON response containing the generated invitation token.
   */
  createInviteToken(ctx: Context): Promise<CreateInviteResponse>;

  /**
   * Verifies an invitation token and adds the user to the corresponding group if the token is valid.
   * The user will be added with the "MEMBER" role in the group.
   *
   * @param ctx - The context of the HTTP request, containing the invitation token and user details.
   * @returns A promise that resolves to a JSON response confirming that the user has been successfully added to the group.
   */
  verifyInviteToken(ctx: Context): Promise<VerifyTokenResponse>;
}

export class InvitationControllerImpl implements InvitationController {
  private invitationService: InvitationService;

  constructor(invitationService: InvitationService) {
    this.invitationService = invitationService;
  }

  async verifyInviteToken(ctx: Context): Promise<VerifyTokenResponse> {
    const verifyInviteTokenImpl = async () => {
      const userId = ctx.get("userId");
      const token = ctx.req.param("token");
      await this.invitationService.verifyInviteToken(token, userId);
      return ctx.json({ message: "Successfully added to group" }, Status.OK);
    };
    return await handleAppError(verifyInviteTokenImpl)(ctx);
  }

  async createInviteToken(ctx: Context): Promise<CreateInviteResponse> {
    const createInviteTokenImpl = async () => {
      const groupId = ctx.req.param("groupId");
      const groupIdAsUUID = parseUUID(groupId);
      const userId = ctx.get("userId");
      const invite = await this.invitationService.createInviteToken(groupIdAsUUID, userId);
      return ctx.json(invite, Status.OK);
    };
    return await handleAppError(createInviteTokenImpl)(ctx);
  }
}
