name: EAS Deployment Build

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
          
      - name: Install dependencies
        run: cd frontend && bun install

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build on EAS and Auto-Submit to App Store if successful
        run: cd frontend && eas build --platform ios --non-interactive --no-wait --profile production --auto-submit
