name: Frontend Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  should-run-checks:
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.draft == false &&
      github.actor != 'dependabot[bot]'
    outputs:
      should-run: ${{ steps.check.outputs.should-run }}
    steps:
      - id: check
        run: echo "should-run=true" >> $GITHUB_OUTPUT

  frontend-checks:
    needs: should-run-checks
    if: needs.should-run-checks.outputs.should-run == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        
      - name: Install dependencies
        run: cd frontend && bun install

      - name: Install Prettier
        run: cd frontend && bun add -D prettier
        
      - name: Check formatting
        run: cd frontend && bun format:check
        
      - name: Run linter
        run: cd frontend && bun lint:fix
