name: Frontend CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  frontend-checks:
    if: |
      github.event.pull_request.draft == false &&
      github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        
      - name: Install dependencies
        run: cd frontend && bun install

      - name: Install Prettier
        run: cd frontend && bun add -D prettier
        
      - name: Check formatting
        run: cd frontend && bun format:check
        
      - name: Run linter
        run: cd frontend && bun lint:fix
